name: 🚀 Dothome Deploy

on:
  push:
    branches: [ master ]

jobs:
  web-deploy:
    name: 🎉 Deploy to Dothome
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code from Git
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: recoba00.dothome.co.kr     # 원래 계정 주소로 복원
          username: recoba00                 # 원래 계정 아이디로 복원
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: html/our_share/